# Generated by Django 3.2.12 on 2022-03-21 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('start_dt', models.DateField()),
                ('end_dt', models.DateField(null=True)),
                ('cancel_dt', models.DateField(null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('clients', models.ManyToManyField(related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_modified_last', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
